use crate::error::{FlapjackError, Result};
use aes_gcm_siv::aead::{Aead, KeyInit, Payload};
use aes_gcm_siv::{Aes256GcmSiv, Nonce};
use flate2::read::GzDecoder;
use flate2::write::GzEncoder;
use flate2::Compression;
use rand::RngCore;
use std::fs::File;
use std::io::Read;
use std::path::{Component, Path};
use tar::{Archive, Builder};

const SNAPSHOT_KEY_FILE_ENV: &str = "FLAPJACK_SNAPSHOT_KEY_FILE";

// These constants define an on-disk/on-wire format and are not free to change.
const SNAPSHOT_ENCRYPTION_MAGIC: &[u8; 8] = b"FJSNAPE1";
const SNAPSHOT_ENCRYPTION_VERSION: u8 = 1;
const SNAPSHOT_ENCRYPTION_NONCE_LEN: usize = 12;
const SNAPSHOT_ENCRYPTION_HEADER_LEN: usize = 21;

fn reject_invalid_snapshot_entry_path(entry_path: &Path) -> Result<()> {
    if entry_path.is_absolute() {
        return Err(crate::error::FlapjackError::InvalidDocument(format!(
            "snapshot entry path must be relative: {}",
            entry_path.display()
        )));
    }

    for component in entry_path.components() {
        if matches!(
            component,
            Component::ParentDir | Component::RootDir | Component::Prefix(_)
        ) {
            return Err(crate::error::FlapjackError::InvalidDocument(format!(
                "snapshot entry path escapes destination: {}",
                entry_path.display()
            )));
        }
    }

    Ok(())
}

fn validate_archive_entries<R: std::io::Read>(archive: &mut Archive<R>) -> Result<()> {
    for entry_result in archive.entries()? {
        let mut entry = entry_result?;
        let entry_path = entry.path()?.into_owned();
        reject_invalid_snapshot_entry_path(&entry_path)?;

        // Links can pivot writes outside the destination tree at extraction time.
        // Reject link entries so snapshot imports are fail-closed by default.
        let entry_type = entry.header().entry_type();
        if entry_type.is_symlink() || entry_type.is_hard_link() {
            return Err(crate::error::FlapjackError::InvalidDocument(format!(
                "snapshot archive contains unsupported link entry: {}",
                entry_path.display()
            )));
        }

        // Reading only the headers can accept a tar entry whose declared payload
        // was truncated while the source index was changing underneath export.
        // Drain every payload so validation proves that the bytes import will
        // consume are actually present, not merely that their paths are safe.
        std::io::copy(&mut entry, &mut std::io::sink())?;
    }

    Ok(())
}

fn validate_snapshot_bytes(data: &[u8]) -> Result<()> {
    let decoder = GzDecoder::new(data);
    let mut archive = Archive::new(decoder);
    validate_archive_entries(&mut archive)
}

pub fn export_to_tarball(index_path: &Path, dest_file: &Path) -> Result<u64> {
    let file = File::create(dest_file)?;
    let encoder = GzEncoder::new(file, Compression::fast());
    let mut archive = Builder::new(encoder);

    archive.append_dir_all(".", index_path)?;

    let encoder = archive.into_inner()?;
    encoder.finish()?;

    let size = std::fs::metadata(dest_file)?.len();
    Ok(size)
}

pub fn import_from_tarball(tarball_path: &Path, dest_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(dest_dir)?;

    let validation_file = File::open(tarball_path)?;
    let validation_decoder = GzDecoder::new(validation_file);
    let mut validation_archive = Archive::new(validation_decoder);
    validate_archive_entries(&mut validation_archive)?;

    let file = File::open(tarball_path)?;
    let decoder = GzDecoder::new(file);
    let mut archive = Archive::new(decoder);

    archive.unpack(dest_dir)?;

    Ok(())
}

fn build_plaintext_snapshot_bytes(index_path: &Path) -> Result<Vec<u8>> {
    let mut buffer = Vec::new();
    {
        let encoder = GzEncoder::new(&mut buffer, Compression::fast());
        let mut archive = Builder::new(encoder);
        archive.append_dir_all(".", index_path)?;
        let encoder = archive.into_inner()?;
        encoder.finish()?;
    }
    // A live Tantivy directory can churn while tar walks it. Never publish
    // generated bytes until a complete decode has consumed every entry. HTTP
    // callers can then retry the resulting transient I/O error instead of
    // returning a snapshot that fails later at import_extract.
    validate_snapshot_bytes(&buffer)?;
    Ok(buffer)
}

fn snapshot_key_file_error(message: impl Into<String>) -> FlapjackError {
    FlapjackError::Config(format!(
        "{SNAPSHOT_KEY_FILE_ENV} key file: {}",
        message.into()
    ))
}

fn parse_snapshot_key(file_bytes: &[u8]) -> Result<[u8; 32]> {
    let key_bytes = match file_bytes.len() {
        32 | 64 => file_bytes,
        33 | 65 if file_bytes.ends_with(b"\n") => &file_bytes[..file_bytes.len() - 1],
        _ => {
            return Err(snapshot_key_file_error(
                "expected exactly 64 hex characters or 32 raw bytes, with at most one trailing newline",
            ));
        }
    };

    let mut key = [0u8; 32];
    match key_bytes.len() {
        32 => key.copy_from_slice(key_bytes),
        64 => {
            let decoded = hex::decode(key_bytes).map_err(|_| {
                snapshot_key_file_error(
                    "expected exactly 64 hex characters or 32 raw bytes, with at most one trailing newline",
                )
            })?;
            key.copy_from_slice(&decoded);
        }
        _ => unreachable!("snapshot key length was validated above"),
    }
    Ok(key)
}

fn resolve_snapshot_key_file() -> Result<Option<[u8; 32]>> {
    let Some(key_path) = std::env::var_os(SNAPSHOT_KEY_FILE_ENV) else {
        return Ok(None);
    };
    let key_path = Path::new(&key_path);
    let key_file = File::open(key_path).map_err(|error| {
        snapshot_key_file_error(format!("could not open {}: {error}", key_path.display()))
    })?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        let mode = key_file
            .metadata()
            .map_err(|error| snapshot_key_file_error(format!("could not inspect mode: {error}")))?
            .permissions()
            .mode();
        if mode & 0o077 != 0 {
            tracing::warn!(
                path = %key_path.display(),
                mode = format_args!("{:#o}", mode & 0o777),
                "snapshot encryption key file is accessible by group or other users"
            );
        }
    }

    let mut file_bytes = Vec::with_capacity(66);
    key_file
        .take(66)
        .read_to_end(&mut file_bytes)
        .map_err(|error| snapshot_key_file_error(format!("could not be read: {error}")))?;
    parse_snapshot_key(&file_bytes).map(Some)
}

fn encrypt_snapshot_bytes(plaintext: &[u8], key: &[u8; 32]) -> Result<Vec<u8>> {
    let cipher = Aes256GcmSiv::new_from_slice(key)
        .map_err(|error| FlapjackError::Config(format!("invalid snapshot key: {error}")))?;
    let mut nonce_bytes = [0u8; SNAPSHOT_ENCRYPTION_NONCE_LEN];
    rand::thread_rng().fill_bytes(&mut nonce_bytes);

    let mut envelope = Vec::with_capacity(SNAPSHOT_ENCRYPTION_HEADER_LEN);
    envelope.extend_from_slice(SNAPSHOT_ENCRYPTION_MAGIC);
    envelope.push(SNAPSHOT_ENCRYPTION_VERSION);
    envelope.extend_from_slice(&nonce_bytes);
    let ciphertext = cipher
        .encrypt(
            Nonce::from_slice(&nonce_bytes),
            Payload {
                msg: plaintext,
                aad: &envelope,
            },
        )
        .map_err(|error| {
            FlapjackError::Config(format!("snapshot AEAD encryption failed: {error}"))
        })?;
    envelope.extend_from_slice(&ciphertext);
    Ok(envelope)
}

fn decrypt_snapshot_bytes(envelope: &[u8], key: &[u8; 32]) -> Result<Vec<u8>> {
    if envelope.len() < SNAPSHOT_ENCRYPTION_HEADER_LEN {
        return Err(FlapjackError::Config(
            "encrypted snapshot envelope is truncated".to_string(),
        ));
    }
    let version = envelope[SNAPSHOT_ENCRYPTION_MAGIC.len()];
    if version != SNAPSHOT_ENCRYPTION_VERSION {
        return Err(FlapjackError::Config(format!(
            "unsupported snapshot encryption version {version}"
        )));
    }

    let cipher = Aes256GcmSiv::new_from_slice(key)
        .map_err(|error| FlapjackError::Config(format!("invalid snapshot key: {error}")))?;
    let nonce_start = SNAPSHOT_ENCRYPTION_MAGIC.len() + 1;
    let nonce_end = nonce_start + SNAPSHOT_ENCRYPTION_NONCE_LEN;
    cipher
        .decrypt(
            Nonce::from_slice(&envelope[nonce_start..nonce_end]),
            Payload {
                msg: &envelope[SNAPSHOT_ENCRYPTION_HEADER_LEN..],
                aad: &envelope[..SNAPSHOT_ENCRYPTION_HEADER_LEN],
            },
        )
        .map_err(|error| {
            FlapjackError::Config(format!(
                "snapshot AEAD authentication/decryption failed: {error}"
            ))
        })
}

pub fn export_to_bytes(index_path: &Path) -> Result<Vec<u8>> {
    // Keep this production-call signature stable while configuration stays file-backed.
    let key = resolve_snapshot_key_file()?;
    export_to_bytes_with_key(index_path, key.as_ref())
}

pub fn export_to_bytes_with_key(index_path: &Path, key: Option<&[u8; 32]>) -> Result<Vec<u8>> {
    let plaintext = build_plaintext_snapshot_bytes(index_path)?;
    match key {
        None => Ok(plaintext),
        Some(key) => encrypt_snapshot_bytes(&plaintext, key),
    }
}

pub fn import_from_bytes(data: &[u8], dest_dir: &Path) -> Result<()> {
    // Keep this production-call signature stable while configuration stays file-backed.
    let key = resolve_snapshot_key_file()?;
    import_from_bytes_with_key(data, dest_dir, key.as_ref())
}

pub fn import_from_bytes_with_key(
    data: &[u8],
    dest_dir: &Path,
    key: Option<&[u8; 32]>,
) -> Result<()> {
    let decrypted;
    let plaintext = if data.starts_with(SNAPSHOT_ENCRYPTION_MAGIC) {
        let key = key.ok_or_else(|| {
            snapshot_key_file_error("is required to import an encrypted snapshot")
        })?;
        // Decrypt first because validate_snapshot_bytes is the SD-008 traversal guard
        // and must inspect attacker-controlled plaintext before archive extraction.
        decrypted = decrypt_snapshot_bytes(data, key)?;
        decrypted.as_slice()
    } else {
        data
    };

    std::fs::create_dir_all(dest_dir)?;
    validate_snapshot_bytes(plaintext)?;

    let decoder = GzDecoder::new(plaintext);
    let mut archive = Archive::new(decoder);
    archive.unpack(dest_dir)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::index::version_store::{VersionRecord, VersionStore};
    use std::fs;
    use tempfile::TempDir;

    /// Verify that exporting a directory tree to a gzipped tarball and re-importing it preserves both flat files and nested subdirectory contents.
    #[test]
    fn test_tarball_roundtrip() {
        let src = TempDir::new().unwrap();
        let dest = TempDir::new().unwrap();

        fs::write(src.path().join("test.txt"), "hello world").unwrap();
        fs::create_dir(src.path().join("subdir")).unwrap();
        fs::write(src.path().join("subdir/nested.txt"), "nested content").unwrap();

        let tarball = dest.path().join("export.tar.gz");
        export_to_tarball(src.path(), &tarball).unwrap();

        let restored = TempDir::new().unwrap();
        import_from_tarball(&tarball, restored.path()).unwrap();

        assert_eq!(
            fs::read_to_string(restored.path().join("test.txt")).unwrap(),
            "hello world"
        );
        assert_eq!(
            fs::read_to_string(restored.path().join("subdir/nested.txt")).unwrap(),
            "nested content"
        );
    }

    #[test]
    fn test_bytes_roundtrip() {
        let src = TempDir::new().unwrap();
        fs::write(src.path().join("data.json"), r#"{"key": "value"}"#).unwrap();

        let bytes = export_to_bytes(src.path()).unwrap();
        assert!(!bytes.is_empty());

        let restored = TempDir::new().unwrap();
        import_from_bytes(&bytes, restored.path()).unwrap();

        assert_eq!(
            fs::read_to_string(restored.path().join("data.json")).unwrap(),
            r#"{"key": "value"}"#
        );
    }

    #[test]
    fn version_store_survives_snapshot_export_import_roundtrip() {
        let source = TempDir::new().unwrap();
        let live = VersionRecord::new(1_700_000_000_001, "node-a", false, 17);
        let deleted = VersionRecord::new(1_700_000_000_002, "node-b", true, 18);
        {
            let store = VersionStore::open(source.path()).unwrap();
            assert!(store.upsert("live-object", &live).unwrap());
            assert!(store.upsert("deleted-object", &deleted).unwrap());
        }

        let bytes = export_to_bytes(source.path()).unwrap();
        let restored = TempDir::new().unwrap();
        import_from_bytes(&bytes, restored.path()).unwrap();

        let store = VersionStore::open(restored.path()).unwrap();
        assert_eq!(store.get("live-object").unwrap(), Some(live));
        assert_eq!(store.get("deleted-object").unwrap(), Some(deleted));
    }

    #[test]
    fn generated_snapshot_validation_rejects_truncated_entry_payload() {
        let src = TempDir::new().unwrap();
        fs::write(src.path().join("payload.bin"), vec![0x5a; 64 * 1024]).unwrap();

        let mut bytes = export_to_bytes(src.path()).unwrap();
        bytes.truncate(bytes.len() / 2);

        assert!(
            validate_snapshot_bytes(&bytes).is_err(),
            "a truncated generated archive must fail before publication"
        );
    }

    #[test]
    fn snapshot_key_parser_accepts_raw_key_with_trailing_newline() {
        let expected = [0xa5; 32];
        let mut file_bytes = expected.to_vec();
        file_bytes.push(b'\n');

        assert_eq!(parse_snapshot_key(&file_bytes).unwrap(), expected);
    }

    #[test]
    fn snapshot_key_parser_rejects_unrecognized_shape_with_accepted_forms() {
        let error = parse_snapshot_key(b"too-short\n").unwrap_err();
        let message = error.to_string();

        assert!(message.contains("64 hex characters"), "{message}");
        assert!(message.contains("32 raw bytes"), "{message}");
    }
}
