// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { BatchSearchLegacyResponse } from './batchSearchLegacyResponse';
import type { FederatedResponse } from './federatedResponse';

export type BatchSearchResponse<T = Record<string, unknown>> =
  | BatchSearchLegacyResponse<T>
  | FederatedResponse<T>;
