// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { SearchResult } from './searchResult';

export type BatchSearchLegacyResponse<T = Record<string, unknown>> = {
  results: SearchResult<T>[];
};
