// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { FederatedHit } from './federatedHit';

export type FederatedResponse<T = Record<string, unknown>> = {
  estimatedTotalHits: number;

  hits: FederatedHit<T>[];

  limit: number;

  offset: number;

  processingTimeMS?: number | undefined;
};
