// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

export type FederationConfig = {
  limit?: number | undefined;

  mergeFacets?: Record<string, any> | null | undefined;

  offset?: number | undefined;
};
