// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { FederationMeta } from './federationMeta';
import type { Hit } from './hit';

export type FederatedHit<T = Record<string, unknown>> = Hit<T> & {
  _federation: FederationMeta;
};
