// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { FederationConfig } from './federationConfig';
import type { SearchQuery } from './searchQuery';
import type { SearchStrategy } from './searchStrategy';


export type SearchMethodParams =  {

    federation?:       FederationConfig
    | undefined
 ;

    requests:       Array<SearchQuery>
 ;

    strategy?:       SearchStrategy
    | undefined
 ;
} 


