// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { FederationOptions } from './federationOptions';
import type { SearchTypeDefault } from './searchTypeDefault';


export type SearchForHitsOptions =  {

    federationOptions?:       FederationOptions
    | undefined
 ;

    /**
    * Index name (case-sensitive).
    */
    indexName:       string
 ;

    type?:       SearchTypeDefault
    | undefined
 ;
}  & { facet?: never | undefined; maxFacetHits?: never | undefined; facetQuery?: never | undefined}; 


