//! Query datasets used by the demo analytics generator.

/// Default search queries for when we don't know the index content.
pub(super) const DEFAULT_QUERIES: &[(&str, u32, bool)] = &[
    // (query, approx_hits, has_results)
    ("", 500, true), // Browse / empty query
    ("shoes", 42, true),
    ("blue dress", 18, true),
    ("laptop", 35, true),
    ("wireless headphones", 12, true),
    ("running shoes", 28, true),
    ("iphone case", 15, true),
    ("organic coffee", 8, true),
    ("winter jacket", 22, true),
    ("smart watch", 19, true),
    ("bluetooth speaker", 14, true),
    ("yoga mat", 7, true),
    ("backpack", 25, true),
    ("sunglasses", 31, true),
    ("water bottle", 11, true),
    ("desk lamp", 9, true),
    ("keyboard", 16, true),
    ("monitor", 20, true),
    ("camera", 13, true),
    ("headset", 17, true),
    ("tablet", 23, true),
    ("charger", 10, true),
    ("mouse pad", 6, true),
    ("office chair", 4, true),
    ("standing desk", 3, true),
    ("batman", 5, true),
    // Queries that return no results
    ("free download", 0, false),
    ("asdfghjkl", 0, false),
    ("buy cheap online free", 0, false),
    ("lorem ipsum", 0, false),
    ("test123", 0, false),
    ("xxxxxxx", 0, false),
];

/// Movies-themed queries for movie demo databases.
pub(super) const MOVIE_QUERIES: &[(&str, u32, bool)] = &[
    ("", 1000, true),
    ("batman", 15, true),
    ("comedy", 180, true),
    ("sci fi", 120, true),
    ("tom hanks", 22, true),
    ("action", 250, true),
    ("romance", 95, true),
    ("thriller", 110, true),
    ("horror", 80, true),
    ("marvel", 28, true),
    ("animation", 65, true),
    ("documentary", 45, true),
    ("star wars", 12, true),
    ("james bond", 18, true),
    ("christopher nolan", 10, true),
    ("drama", 300, true),
    ("adventure", 140, true),
    ("crime", 75, true),
    ("musical", 30, true),
    ("western", 20, true),
    ("tarantino", 8, true),
    ("spielberg", 14, true),
    ("pixar", 16, true),
    ("oscar", 35, true),
    ("2024", 40, true),
    ("new release", 0, false),
    ("stream free", 0, false),
    ("torrent", 0, false),
    ("subtitles", 0, false),
];

/// Product-themed queries for e-commerce demo databases.
pub(super) const PRODUCT_QUERIES: &[(&str, u32, bool)] = &[
    ("", 800, true),
    ("samsung", 45, true),
    ("apple", 38, true),
    ("laptop", 62, true),
    ("phone", 55, true),
    ("headphones", 30, true),
    ("tv", 42, true),
    ("camera", 25, true),
    ("wireless", 48, true),
    ("bluetooth", 35, true),
    ("gaming", 28, true),
    ("keyboard", 20, true),
    ("monitor", 32, true),
    ("speaker", 18, true),
    ("tablet", 22, true),
    ("earbuds", 15, true),
    ("charger", 12, true),
    ("mouse", 17, true),
    ("printer", 10, true),
    ("router", 8, true),
    ("usb", 14, true),
    ("hdmi", 6, true),
    ("webcam", 9, true),
    ("microphone", 11, true),
    ("ssd", 7, true),
    ("free shipping", 0, false),
    ("coupon code", 0, false),
    ("refurbished xyz123", 0, false),
    ("wholesale bulk", 0, false),
];
